// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.ProductAPI.Model.Context;

#nullable disable

namespace eShop.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eShop.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Copos",
                            Description = "Copo Mário ideal para tomar suco e refrigerante.",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Glass_Mario.jpg",
                            Name = "Copo Mário",
                            Price = 35.45m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Copos",
                            Description = "Copo Mickey ideal para tomar suco e refrigerante.",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Glass_Mickey.jpg",
                            Name = "Copo Mickey",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Mouse Pad",
                            Description = "Mouse Pad Gamer Diablo ideal para jogos.",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Mouse_Pad_Diablo.jpg",
                            Name = "Mouse Pad Diablo",
                            Price = 35.45m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Mouse Pad",
                            Description = "Mouse Pad Gamer Mortal Kombat ideal para jogos.",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Mouse_Pad_Mortal_Kombat.jpg",
                            Name = "Mouse Pad Mortal Kombat",
                            Price = 195.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Mouse Pad",
                            Description = "Mouse Pad Gamer Sonic ideal para jogos.",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Mouse_Pad_Sonic.jpg",
                            Name = "Mouse Pad Sonic",
                            Price = 89.00m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Camisas",
                            Description = "Camisa customizada Donkey Kong",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/T-Shirt_Donkey_Kong.jpg",
                            Name = "Camisa Donkey Kong",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Camisas",
                            Description = "Camisa customizada Gamer",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/T-Shirt_Gamer.jpg",
                            Name = "Camisa Gamer",
                            Price = 15.45m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Camisas",
                            Description = "Camisa customizada Cavaleiro",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/T-Shirt_Cavaleiro.jpg",
                            Name = "Camisa Cavaleiro",
                            Price = 115.45m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Tolhas",
                            Description = "Tolha de Banho customizada Castlevania",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Towel_Castlevania.jpg",
                            Name = "Toalha Castlevania",
                            Price = 87.56m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Tolhas",
                            Description = "Tolha de Banho customizada Gamer",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Towel_Gamer.jpg",
                            Name = "Toalha Gamer",
                            Price = 89.45m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Tolhas",
                            Description = "Tolha de Banho customizada Naruto",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Towel_Naruto.jpg",
                            Name = "Toalha Naruto",
                            Price = 135.99m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Tolhas",
                            Description = "Tolha de Banho customizada Popeye",
                            ImageUrl = "https://github.com/dnrNew/e-shop-microservice/blob/eShop/eShopMicroservice/eShopImages/Towel_Popeye.jpg",
                            Name = "Toalha Popeye",
                            Price = 250.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
